trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, World!
  displayName: 'Run a one-line script'

- script:
    echo Add other tasks to build, test, and deploy your project.
    echo See http://aka.ms/yaml
  displayName: 'Run a mulit-line script'

- task: Docker@2
  inputs:
    containerRegistry: 'dotnetmssqlrm554773'
    repository: 'dotnetsql'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest